backend:
  name: git-gateway
  branch: main

media_folder: 'images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'blog'
    create: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}