backend:
  name: git-gateway
  branch: main

site_url: https://writezon.it
display_url: https://writezon.it

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articoli"
    label: "Articoli"
    folder: "content/articoli"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
